### ISSUE TITLE
upgrade packages plans 

### ISSUE THREAD

**Issue by luoyunchong** [TeleSoftas/serilog-sinks-mariadb#11]
Hello, do you have any plans to upgrade these software packages

- add netstandard2.1 support
- upgrade package mysqlconnector 1.0 
- upgrade packcage Serilog
- upgrade packcage  Serilog.Sinks.PeriodicBatching

Thank you

**Comment by Dissimilis** [comment]
We will probably do that, but feel free to create PR yourself.
Why are you missing netstandard2.1 specifically? Our goal was to target lowest possible netstandard version.

**Comment by luoyunchong** [comment]
Hi,Netstandard 2.1 is not required，but .net core 1.x  is End of life.
we can upgrade it to netstandard2.0 .

The MySQL connector 1.0 namespace has changed and cannot be used with other class libraries because they are upgraded to MySQL connector 1.0

**Comment by Dissimilis** [comment]
@luoyunchong targeting netstandard1.6 just tells that this library is ok with limited API which is defined by netstardard1.6. netstandard2.0, 2.1 and all future versions should include netstandard1.6 API anyway, so we will not gain anything by targeting a more recent netstandard version. Or am I missing something?

**Comment by luoyunchong** [comment]
hi !

There are two drivers for. Net core to access mysql。

One is mysql.data , and the other is mysqlconnector


.net core 访问mysql 有二个驱动 ，一个是mysql.data,一个是mysqlconnector。因为API设计是一样的，是能够通过条件编译，同时支持这二个类库呢。

**Comment by luoyunchong** [comment]
using Link file ,like  this repository   https://github.com/dotnetcore/FreeSql/blob/master/Providers/FreeSql.Provider.MySqlConnector/FreeSql.Provider.MySqlConnector.csproj

![image](https://user-images.githubusercontent.com/18613266/96002101-5416c500-0e6b-11eb-88aa-80d005394a05.png)

```
	<ItemGroup>
		<Compile Include="../FreeSql.Provider.MySql/**/*.cs" Exclude="../FreeSql.Provider.MySql/obj/**/*" />
	</ItemGroup>
```

**Comment by miezis** [comment]
Closing due to https://github.com/TeleSoftas/serilog-sinks-mariadb/pull/13#issuecomment-812537738
