### ISSUE TITLE
How can I add a custom column

### ISSUE THREAD

**Issue by bakbuz** [TeleSoftas/serilog-sinks-mariadb#12]
How can I add the UserId column in Logs table adn push userId value?

I created a middleware but that's doesn't work.

Thanks
Sincerely.

```
    public class SerilogMiddleware
    {
        private readonly RequestDelegate next;

        public SerilogMiddleware(RequestDelegate next)
        {
            this.next = next;
        }

        public Task Invoke(HttpContext context)
        {
            var userIdentifier = context.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);

            LogContext.PushProperty("UserId", userIdentifier?.Value);

            return next(context);
        }
    }
```

**Comment by miezis** [comment]
@bakbuz You should achieve this by modifying the [`PropertiesToColumnsMapping`](https://github.com/TeleSoftas/serilog-sinks-mariadb#propertiestocolumnsmapping) property of `MariaDBSinkOptions`.

For example:

```
.WriteTo.MariaDB(
    ...
    options: new MariaDBSinkOptions
    {
        ...
        PropertiesToColumnsMapping =
        {
            ...
            ["UserId"] = "ColumnNameInDatabase",
            ...
        },
        ...
    }
    ...
)
```

**Comment by bakbuz** [comment]
> @bakbuz You should achieve this by modifying the [`PropertiesToColumnsMapping`](https://github.com/TeleSoftas/serilog-sinks-mariadb#propertiestocolumnsmapping) property of `MariaDBSinkOptions`.
> 
> For example:
> 
> ```
> .WriteTo.MariaDB(
>     ...
>     options: new MariaDBSinkOptions
>     {
>         ...
>         PropertiesToColumnsMapping =
>         {
>             ...
>             ["UserId"] = "ColumnNameInDatabase",
>             ...
>         },
>         ...
>     }
>     ...
> )
> ```

Thanks.
