### ISSUE TITLE
Serilog.Sinks.MariaDb with Android

### ISSUE THREAD

**Issue by Hardshop18** [TeleSoftas/serilog-sinks-mariadb#15]
hello, I'm using Serilog.Sinks.MariaDb with Android, but I wasn't successful in logging.
Example of my code:

`var serilog = new LoggerConfiguration()`
`                      .Enrich.FromLogContext()`
`                      .WriteTo.MariaDb(`
`                          connectionString: "Server=localhost;Port=3306;Database=teste;User Id=root;Password=root;Convert Zero Datetime=True;Pooling=True;Use Affected Rows=False",`
`                          autoCreateTable: True,`
`                          restrictedToMinimumLevel: LogEventLevel.Debug);`
` `
`var loggerFactory = LoggerFactory.Create(builder => builder.AddSerilog(serilog))`
`                         .SetMinimumLevel(LogLevel.Debug);`
` `
`loggerFactory.CreateLogger("Log");`

**Comment by Hardshop18** [comment]
Using Serilog.Debugging.Selflog I got the following error: 
**`"unable to write 2 log events to the database due to following error: index was outside the bounds of the array."`**
I'm trying to record 2 logs.

**Comment by miezis** [comment]
Hi @Hardshop18 , could you provide a sample project that would reproduce this output? It'd be helpful trying to find a root cause.
